name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Check import
      run: |
        python -c "import claire; print(f'CLAIRE version: {claire.__version__}')"
    
    - name: Lint check (non-blocking)
      continue-on-error: true
      run: |
        pip install flake8
        # Only check for critical errors
        flake8 claire --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Run minimal tests if available
      continue-on-error: true
      run: |
        if [ -d "tests" ] && [ -n "$(ls -A tests/*.py 2>/dev/null)" ]; then
          pip install pytest
          pytest tests/ -v || echo "Tests failed but continuing"
        else
          echo "No tests found, skipping"
        fi